chore(deps): bump redb from 2.6.3 to 3.1.0 (#18)
Bumps [redb](https://github.com/cberner/redb) from 2.6.3 to 3.1.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/cberner/redb/releases">redb's
releases</a>.</em></p>
<blockquote>
<h2>3.1.0</h2>
<ul>
<li>Implement <code>std::error::Error</code> for
<code>SetDurabilityError</code></li>
<li>Fix compilation error on various non-tier-1 platforms, such as
wasm32-unknown</li>
</ul>
<h2>3.0.2</h2>
<ul>
<li>Fix performance issue where a transaction with a large number of
writes would cause
<code>WriteTransaction::abort()</code> and committing non-durable
transactions to become slow</li>
</ul>
<h2>3.0.1</h2>
<ul>
<li>Fix correctness issue with <code>range()</code>,
<code>extract_from_if()</code>, and <code>retain_in()</code>. If a
RangeBounds
with <code>start</code> &gt; <code>end</code> was passed as an argument
and <code>start</code> and <code>end</code> keys were stored in
different
internal pages in the database (i.e. a sufficient condition is that more
than 4KiB of key-value
pairs were between the two keys) then these methods would perform as if
the argument had been
<code>start..</code></li>
<li>Fix performance regression, from redb 2.x, where
<code>Durability::None</code> commits could become linearly
slower during a series of transactions.</li>
</ul>
<h2>3.0.0 - 2025-08-09</h2>
<h3>Removes support for file format v2.</h3>
<p>Use <code>Database::upgrade()</code>, in redb 2.6, to migrate to the
v3 file format.</p>
<h3>General storage optimizations</h3>
<p>The v3 file format has been further optimized to reduce the size of
the database. Databases with only
a few small keys will see the largest benefit, and the minimum size of a
database file has decreased
from ~2.5MiB to ~50KiB. To achieve the smallest file size call
<code>Database::compact()</code> before
dropping the <code>Database</code>.</p>
<p>Additionally, performance is ~15% better in bulk load benchmarks.
This was achieved by implementing
a custom hash function for various in-memory <code>HashSet</code>s and
<code>HashMap</code>s, and by optimizing the usage
of buffers held in <code>Arc</code>s to reduce the number of atomic
instructions executed.</p>
<h3>Optimize storage of tuple types</h3>
<p>Storage of variable width tuple types with arity greater than 1 is
more efficient. The new format
elides the length of any fixed width fields and uses varint encoding for
the lengths of all variable
width fields.</p>
<p>Note that this encoding is not compatible with the serialization of
variable width tuples used in prior versions.
To load tuple data created prior to version 3.0, wrap them in the
<code>Legacy</code> type.
For example, <code>TableDefinition&lt;u64, (&amp;str, u32)&gt;</code>
becomes <code>TableDefinition&lt;u64, Legacy&lt;(&amp;str,
u32)&gt;&gt;</code>.
Fixed width tuples, such as <code>(u32, u64)</code> are backwards
compatible.</p>
<h3>Derive for Key and Value traits</h3>
<p><code>Key</code> and <code>Value</code> can be derived using the
<code>redb-derive</code> crate. Note that it does not support
schema migration. The recommended pattern to migrate schema is to create
a new table, and then
perform a migration from the old table to the new table.</p>
<h3>Read-only multi-process support</h3>
<p>Multiple processes may open the same database file for reading by
using the new <code>ReadOnlyDatabase</code>
type. On platforms which support file locks, this acquires a shared lock
on the database file.</p>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/cberner/redb/blob/master/CHANGELOG.md">redb's
changelog</a>.</em></p>
<blockquote>
<h2>3.1.0 - 2025-09-25</h2>
<ul>
<li>Implement <code>std::error::Error</code> for
<code>SetDurabilityError</code></li>
<li>Fix compilation error on various non-tier-1 platforms, such as
wasm32-unknown</li>
</ul>
<h2>3.0.2 - 2025-09-16</h2>
<ul>
<li>Fix performance issue where a transaction with a large number of
writes would cause
<code>WriteTransaction::abort()</code> and committing non-durable
transactions to become slow.</li>
</ul>
<h2>3.0.1 - 2025-08-23</h2>
<ul>
<li>Fix correctness issue with <code>range()</code>,
<code>extract_from_if()</code>, and <code>retain_in()</code>. If a
RangeBounds
with <code>start</code> &gt; <code>end</code> was passed as an argument
and <code>start</code> and <code>end</code> keys were stored in
different
internal pages in the database (i.e. a sufficient condition is that more
than 4KiB of key-value
pairs were between the two keys) then these methods would perform as if
the argument had been
<code>start..</code></li>
<li>Fix performance regression, from redb 2.x, where
<code>Durability::None</code> commits could become linearly
slower during a series of transactions.</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/cberner/redb/commit/574f1cf9c5820ebb0097701132341d91bbd1c788"><code>574f1cf</code></a>
Bump version to 3.1.0</li>
<li><a
href="https://github.com/cberner/redb/commit/496c4e80ce59e902887820f13c95d581babb8250"><code>496c4e8</code></a>
Update changelog</li>
<li><a
href="https://github.com/cberner/redb/commit/157ab6236520f48c2a9c38cdecf8d94470781d74"><code>157ab62</code></a>
Implement std::Error for SetDurabilityError</li>
<li><a
href="https://github.com/cberner/redb/commit/0a1b7d9875a936f4a485fa4b324713c4f088a76e"><code>0a1b7d9</code></a>
Move <code>Format</code> and <code>Clippy</code> before any tests</li>
<li><a
href="https://github.com/cberner/redb/commit/3ee20acabe9521b701c07fb753286df8d14b1a05"><code>3ee20ac</code></a>
Replace <code>grep</code> check with equivalent Clippy lints</li>
<li><a
href="https://github.com/cberner/redb/commit/dc247cbc581994b6af2fa8159964a0cd335c8671"><code>dc247cb</code></a>
Run cargo check on <code>wasm32-unknown-unknown</code></li>
<li><a
href="https://github.com/cberner/redb/commit/6c7614530a5ea2f3ec6cbf343b98d09000779fc5"><code>6c76145</code></a>
Implement missing method <code>FileBackend::new_internal</code></li>
<li><a
href="https://github.com/cberner/redb/commit/be5f8fe418811662edea81374a77adcc0d6fdaa6"><code>be5f8fe</code></a>
Bump version to 3.0.2</li>
<li><a
href="https://github.com/cberner/redb/commit/9cc578fc505e0bf1a978721d0d7c66c23fbf6a5a"><code>9cc578f</code></a>
Update changelog</li>
<li><a
href="https://github.com/cberner/redb/commit/3674fc72398bdc664c748f8ad7072cd82c6883f8"><code>3674fc7</code></a>
Improve cache flush performance</li>
<li>Additional commits viewable in <a
href="https://github.com/cberner/redb/compare/v2.6.3...v3.1.0">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=redb&package-manager=cargo&previous-version=2.6.3&new-version=3.1.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Jonathan D.A. Jewell <6759885+hyperpolymath@users.noreply.github.com>